use core::fmt;
use std::fmt::Display;

use ::phf::phf_map;
use phf::phf_set;

#[derive(Eq, Hash, PartialEq, Ord, PartialOrd, Copy, Clone, Debug)]
pub enum Arcana {
    Fool = 1,
    Magician,
    Priestess,
    Empress,
    Emperor,
    Hierophant,
    Lovers,
    Chariot,
    Justice,
    Hermit,
    Fortune,
    Strength,
    Hanged,
    Death,
    Temperance,
    Devil,
    Tower,
    Star,
    Moon,
    Sun,
    Judgement,
    Faith,
    Councillor,
    World,
}

impl Display for Arcana {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

#[derive(Debug, PartialEq, Clone)]
pub struct ArcanaCombination {
    pub first: Arcana,
    pub second: Arcana,
    pub result: Arcana,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct PersonaData {
    pub level: u8,
    pub arcana: Arcana,
}

// Looks like a lot, but not really a large set of data. Might as well just store it on the stack
pub static ARCANA_COMBINATIONS: &[ArcanaCombination] = &[
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Fool,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Magician,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Priestess,
        result: Arcana::Moon,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Empress,
        result: Arcana::Hanged,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Emperor,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Hierophant,
        result: Arcana::Hermit,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Lovers,
        result: Arcana::Chariot,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Chariot,
        result: Arcana::Moon,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Justice,
        result: Arcana::Star,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Hermit,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Fortune,
        result: Arcana::Faith,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Strength,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Hanged,
        result: Arcana::Tower,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Death,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Temperance,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Devil,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Tower,
        result: Arcana::Empress,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Star,
        result: Arcana::Magician,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Moon,
        result: Arcana::Justice,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Sun,
        result: Arcana::Justice,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Judgement,
        result: Arcana::Sun,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Faith,
        result: Arcana::Councillor,
    },
    ArcanaCombination {
        first: Arcana::Fool,
        second: Arcana::Councillor,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Magician,
        result: Arcana::Magician,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Priestess,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Empress,
        result: Arcana::Justice,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Emperor,
        result: Arcana::Faith,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Hierophant,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Lovers,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Chariot,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Justice,
        result: Arcana::Emperor,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Hermit,
        result: Arcana::Lovers,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Fortune,
        result: Arcana::Justice,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Strength,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Hanged,
        result: Arcana::Empress,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Death,
        result: Arcana::Hermit,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Temperance,
        result: Arcana::Chariot,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Devil,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Tower,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Star,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Moon,
        result: Arcana::Lovers,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Sun,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Judgement,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Faith,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Magician,
        second: Arcana::Councillor,
        result: Arcana::Moon,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Priestess,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Empress,
        result: Arcana::Emperor,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Emperor,
        result: Arcana::Empress,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Hierophant,
        result: Arcana::Magician,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Lovers,
        result: Arcana::Fortune,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Chariot,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Justice,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Hermit,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Fortune,
        result: Arcana::Magician,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Strength,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Hanged,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Death,
        result: Arcana::Magician,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Temperance,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Devil,
        result: Arcana::Moon,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Tower,
        result: Arcana::Hanged,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Star,
        result: Arcana::Hermit,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Moon,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Sun,
        result: Arcana::Chariot,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Judgement,
        result: Arcana::Justice,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Faith,
        result: Arcana::Justice,
    },
    ArcanaCombination {
        first: Arcana::Priestess,
        second: Arcana::Councillor,
        result: Arcana::Faith,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Empress,
        result: Arcana::Empress,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Emperor,
        result: Arcana::Justice,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Hierophant,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Lovers,
        result: Arcana::Judgement,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Chariot,
        result: Arcana::Star,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Justice,
        result: Arcana::Lovers,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Hermit,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Fortune,
        result: Arcana::Hermit,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Strength,
        result: Arcana::Faith,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Hanged,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Death,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Temperance,
        result: Arcana::Faith,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Devil,
        result: Arcana::Sun,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Tower,
        result: Arcana::Emperor,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Star,
        result: Arcana::Lovers,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Moon,
        result: Arcana::Fortune,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Sun,
        result: Arcana::Tower,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Judgement,
        result: Arcana::Emperor,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Faith,
        result: Arcana::Magician,
    },
    ArcanaCombination {
        first: Arcana::Empress,
        second: Arcana::Councillor,
        result: Arcana::Hanged,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Emperor,
        result: Arcana::Emperor,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Hierophant,
        result: Arcana::Fortune,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Lovers,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Chariot,
        result: Arcana::Faith,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Justice,
        result: Arcana::Chariot,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Hermit,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Fortune,
        result: Arcana::Sun,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Strength,
        result: Arcana::Tower,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Hanged,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Death,
        result: Arcana::Hermit,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Temperance,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Devil,
        result: Arcana::Justice,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Tower,
        result: Arcana::Star,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Star,
        result: Arcana::Lovers,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Moon,
        result: Arcana::Tower,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Sun,
        result: Arcana::Judgement,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Judgement,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Faith,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Emperor,
        second: Arcana::Councillor,
        result: Arcana::Lovers,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Hierophant,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Lovers,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Chariot,
        result: Arcana::Star,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Justice,
        result: Arcana::Hanged,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Hermit,
        result: Arcana::Councillor,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Fortune,
        result: Arcana::Justice,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Strength,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Hanged,
        result: Arcana::Sun,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Death,
        result: Arcana::Chariot,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Temperance,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Devil,
        result: Arcana::Hanged,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Tower,
        result: Arcana::Judgement,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Star,
        result: Arcana::Tower,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Moon,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Sun,
        result: Arcana::Lovers,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Judgement,
        result: Arcana::Faith,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Faith,
        result: Arcana::Empress,
    },
    ArcanaCombination {
        first: Arcana::Hierophant,
        second: Arcana::Councillor,
        result: Arcana::Justice,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Lovers,
        result: Arcana::Lovers,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Chariot,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Justice,
        result: Arcana::Judgement,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Hermit,
        result: Arcana::Chariot,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Fortune,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Strength,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Hanged,
        result: Arcana::Councillor,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Death,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Temperance,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Devil,
        result: Arcana::Moon,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Tower,
        result: Arcana::Empress,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Star,
        result: Arcana::Faith,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Moon,
        result: Arcana::Magician,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Sun,
        result: Arcana::Empress,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Judgement,
        result: Arcana::Hanged,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Faith,
        result: Arcana::Tower,
    },
    ArcanaCombination {
        first: Arcana::Lovers,
        second: Arcana::Councillor,
        result: Arcana::Tower,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Chariot,
        result: Arcana::Chariot,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Justice,
        result: Arcana::Moon,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Hermit,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Fortune,
        result: Arcana::Councillor,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Strength,
        result: Arcana::Hermit,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Hanged,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Death,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Temperance,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Devil,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Tower,
        result: Arcana::Fortune,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Star,
        result: Arcana::Moon,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Moon,
        result: Arcana::Lovers,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Sun,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Faith,
        result: Arcana::Lovers,
    },
    ArcanaCombination {
        first: Arcana::Chariot,
        second: Arcana::Councillor,
        result: Arcana::Sun,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Justice,
        result: Arcana::Justice,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Hermit,
        result: Arcana::Magician,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Fortune,
        result: Arcana::Emperor,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Strength,
        result: Arcana::Councillor,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Hanged,
        result: Arcana::Lovers,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Death,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Temperance,
        result: Arcana::Emperor,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Devil,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Tower,
        result: Arcana::Sun,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Star,
        result: Arcana::Empress,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Moon,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Sun,
        result: Arcana::Hanged,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Faith,
        result: Arcana::Hanged,
    },
    ArcanaCombination {
        first: Arcana::Justice,
        second: Arcana::Councillor,
        result: Arcana::Emperor,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Hermit,
        result: Arcana::Hermit,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Fortune,
        result: Arcana::Star,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Strength,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Hanged,
        result: Arcana::Star,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Death,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Temperance,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Devil,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Tower,
        result: Arcana::Judgement,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Star,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Moon,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Sun,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Judgement,
        result: Arcana::Emperor,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Faith,
        result: Arcana::Judgement,
    },
    ArcanaCombination {
        first: Arcana::Hermit,
        second: Arcana::Councillor,
        result: Arcana::Faith,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Fortune,
        result: Arcana::Fortune,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Strength,
        result: Arcana::Faith,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Hanged,
        result: Arcana::Emperor,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Death,
        result: Arcana::Star,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Temperance,
        result: Arcana::Empress,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Devil,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Tower,
        result: Arcana::Hanged,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Star,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Moon,
        result: Arcana::Sun,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Sun,
        result: Arcana::Star,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Judgement,
        result: Arcana::Tower,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Faith,
        result: Arcana::Councillor,
    },
    ArcanaCombination {
        first: Arcana::Fortune,
        second: Arcana::Councillor,
        result: Arcana::Judgement,
    },
    ArcanaCombination {
        first: Arcana::Strength,
        second: Arcana::Strength,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Strength,
        second: Arcana::Hanged,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Strength,
        second: Arcana::Death,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Strength,
        second: Arcana::Temperance,
        result: Arcana::Chariot,
    },
    ArcanaCombination {
        first: Arcana::Strength,
        second: Arcana::Devil,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Strength,
        second: Arcana::Tower,
        result: Arcana::Faith,
    },
    ArcanaCombination {
        first: Arcana::Strength,
        second: Arcana::Star,
        result: Arcana::Moon,
    },
    ArcanaCombination {
        first: Arcana::Strength,
        second: Arcana::Moon,
        result: Arcana::Magician,
    },
    ArcanaCombination {
        first: Arcana::Strength,
        second: Arcana::Sun,
        result: Arcana::Moon,
    },
    ArcanaCombination {
        first: Arcana::Strength,
        second: Arcana::Faith,
        result: Arcana::Star,
    },
    ArcanaCombination {
        first: Arcana::Strength,
        second: Arcana::Councillor,
        result: Arcana::Empress,
    },
    ArcanaCombination {
        first: Arcana::Hanged,
        second: Arcana::Hanged,
        result: Arcana::Hanged,
    },
    ArcanaCombination {
        first: Arcana::Hanged,
        second: Arcana::Death,
        result: Arcana::Moon,
    },
    ArcanaCombination {
        first: Arcana::Hanged,
        second: Arcana::Temperance,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Hanged,
        second: Arcana::Devil,
        result: Arcana::Fortune,
    },
    ArcanaCombination {
        first: Arcana::Hanged,
        second: Arcana::Tower,
        result: Arcana::Hermit,
    },
    ArcanaCombination {
        first: Arcana::Hanged,
        second: Arcana::Star,
        result: Arcana::Justice,
    },
    ArcanaCombination {
        first: Arcana::Hanged,
        second: Arcana::Moon,
        result: Arcana::Councillor,
    },
    ArcanaCombination {
        first: Arcana::Hanged,
        second: Arcana::Sun,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Hanged,
        second: Arcana::Judgement,
        result: Arcana::Star,
    },
    ArcanaCombination {
        first: Arcana::Hanged,
        second: Arcana::Faith,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Hanged,
        second: Arcana::Councillor,
        result: Arcana::Star,
    },
    ArcanaCombination {
        first: Arcana::Death,
        second: Arcana::Death,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Death,
        second: Arcana::Temperance,
        result: Arcana::Hanged,
    },
    ArcanaCombination {
        first: Arcana::Death,
        second: Arcana::Devil,
        result: Arcana::Chariot,
    },
    ArcanaCombination {
        first: Arcana::Death,
        second: Arcana::Tower,
        result: Arcana::Sun,
    },
    ArcanaCombination {
        first: Arcana::Death,
        second: Arcana::Star,
        result: Arcana::Councillor,
    },
    ArcanaCombination {
        first: Arcana::Death,
        second: Arcana::Moon,
        result: Arcana::Hierophant,
    },
    ArcanaCombination {
        first: Arcana::Death,
        second: Arcana::Sun,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Death,
        second: Arcana::Faith,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Death,
        second: Arcana::Councillor,
        result: Arcana::Magician,
    },
    ArcanaCombination {
        first: Arcana::Temperance,
        second: Arcana::Temperance,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Temperance,
        second: Arcana::Devil,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Temperance,
        second: Arcana::Tower,
        result: Arcana::Fortune,
    },
    ArcanaCombination {
        first: Arcana::Temperance,
        second: Arcana::Star,
        result: Arcana::Sun,
    },
    ArcanaCombination {
        first: Arcana::Temperance,
        second: Arcana::Moon,
        result: Arcana::Councillor,
    },
    ArcanaCombination {
        first: Arcana::Temperance,
        second: Arcana::Sun,
        result: Arcana::Magician,
    },
    ArcanaCombination {
        first: Arcana::Temperance,
        second: Arcana::Judgement,
        result: Arcana::Hermit,
    },
    ArcanaCombination {
        first: Arcana::Temperance,
        second: Arcana::Faith,
        result: Arcana::Hermit,
    },
    ArcanaCombination {
        first: Arcana::Temperance,
        second: Arcana::Councillor,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Devil,
        second: Arcana::Devil,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Devil,
        second: Arcana::Tower,
        result: Arcana::Magician,
    },
    ArcanaCombination {
        first: Arcana::Devil,
        second: Arcana::Star,
        result: Arcana::Strength,
    },
    ArcanaCombination {
        first: Arcana::Devil,
        second: Arcana::Moon,
        result: Arcana::Chariot,
    },
    ArcanaCombination {
        first: Arcana::Devil,
        second: Arcana::Sun,
        result: Arcana::Hermit,
    },
    ArcanaCombination {
        first: Arcana::Devil,
        second: Arcana::Judgement,
        result: Arcana::Lovers,
    },
    ArcanaCombination {
        first: Arcana::Devil,
        second: Arcana::Faith,
        result: Arcana::Chariot,
    },
    ArcanaCombination {
        first: Arcana::Devil,
        second: Arcana::Councillor,
        result: Arcana::Chariot,
    },
    ArcanaCombination {
        first: Arcana::Tower,
        second: Arcana::Tower,
        result: Arcana::Tower,
    },
    ArcanaCombination {
        first: Arcana::Tower,
        second: Arcana::Star,
        result: Arcana::Councillor,
    },
    ArcanaCombination {
        first: Arcana::Tower,
        second: Arcana::Moon,
        result: Arcana::Hermit,
    },
    ArcanaCombination {
        first: Arcana::Tower,
        second: Arcana::Sun,
        result: Arcana::Emperor,
    },
    ArcanaCombination {
        first: Arcana::Tower,
        second: Arcana::Judgement,
        result: Arcana::Moon,
    },
    ArcanaCombination {
        first: Arcana::Tower,
        second: Arcana::Faith,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Tower,
        second: Arcana::Councillor,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Star,
        second: Arcana::Star,
        result: Arcana::Star,
    },
    ArcanaCombination {
        first: Arcana::Star,
        second: Arcana::Moon,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Star,
        second: Arcana::Sun,
        result: Arcana::Judgement,
    },
    ArcanaCombination {
        first: Arcana::Star,
        second: Arcana::Judgement,
        result: Arcana::Fortune,
    },
    ArcanaCombination {
        first: Arcana::Star,
        second: Arcana::Faith,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Star,
        second: Arcana::Councillor,
        result: Arcana::Sun,
    },
    ArcanaCombination {
        first: Arcana::Moon,
        second: Arcana::Moon,
        result: Arcana::Moon,
    },
    ArcanaCombination {
        first: Arcana::Moon,
        second: Arcana::Sun,
        result: Arcana::Empress,
    },
    ArcanaCombination {
        first: Arcana::Moon,
        second: Arcana::Judgement,
        result: Arcana::Fool,
    },
    ArcanaCombination {
        first: Arcana::Moon,
        second: Arcana::Faith,
        result: Arcana::Sun,
    },
    ArcanaCombination {
        first: Arcana::Moon,
        second: Arcana::Councillor,
        result: Arcana::Temperance,
    },
    ArcanaCombination {
        first: Arcana::Sun,
        second: Arcana::Sun,
        result: Arcana::Sun,
    },
    ArcanaCombination {
        first: Arcana::Sun,
        second: Arcana::Judgement,
        result: Arcana::Death,
    },
    ArcanaCombination {
        first: Arcana::Sun,
        second: Arcana::Faith,
        result: Arcana::Emperor,
    },
    ArcanaCombination {
        first: Arcana::Sun,
        second: Arcana::Councillor,
        result: Arcana::Fortune,
    },
    ArcanaCombination {
        first: Arcana::Judgement,
        second: Arcana::Judgement,
        result: Arcana::Judgement,
    },
    ArcanaCombination {
        first: Arcana::Judgement,
        second: Arcana::Faith,
        result: Arcana::Fortune,
    },
    ArcanaCombination {
        first: Arcana::Judgement,
        second: Arcana::Councillor,
        result: Arcana::Devil,
    },
    ArcanaCombination {
        first: Arcana::Faith,
        second: Arcana::Faith,
        result: Arcana::Faith,
    },
    ArcanaCombination {
        first: Arcana::Faith,
        second: Arcana::Councillor,
        result: Arcana::Priestess,
    },
    ArcanaCombination {
        first: Arcana::Councillor,
        second: Arcana::Councillor,
        result: Arcana::Councillor,
    },
    ArcanaCombination {
        first: Arcana::World,
        second: Arcana::World,
        result: Arcana::World,
    },
];

pub static PERSONAS: phf::Map<&'static str, PersonaData> = phf_map! {
    "Abaddon" => PersonaData { level: 75, arcana: Arcana::Judgement },
    "Agathion" => PersonaData { level: 3, arcana: Arcana::Chariot },
    "Alice" => PersonaData { level: 83, arcana: Arcana::Death },
    "Alilat" => PersonaData { level: 81, arcana: Arcana::Empress },
    "Ame-no-Uzume" => PersonaData { level: 13, arcana: Arcana::Lovers },
    "Ananta" => PersonaData { level: 44, arcana: Arcana::Councillor },
    "Andras" => PersonaData { level: 27, arcana: Arcana::Devil },
    "Angel" => PersonaData { level: 9, arcana: Arcana::Justice },
    "Anubis" => PersonaData { level: 34, arcana: Arcana::Judgement },
    "Anzu" => PersonaData { level: 25, arcana: Arcana::Hierophant },
    "Apsaras" => PersonaData { level: 11, arcana: Arcana::Priestess },
    "Ara Mitama" => PersonaData { level: 30, arcana: Arcana::Chariot },
    "Arahabaki" => PersonaData { level: 35, arcana: Arcana::Hermit },
    "Archangel" => PersonaData { level: 14, arcana: Arcana::Justice },
    "Ardha" => PersonaData { level: 84, arcana: Arcana::Temperance },
    "Arsene" => PersonaData { level: 1, arcana: Arcana::Fool },
    "Asura" => PersonaData { level: 76, arcana: Arcana::Sun },
    "Atavaka" => PersonaData { level: 65, arcana: Arcana::Faith },
    "Atropos" => PersonaData { level: 39, arcana: Arcana::Fortune },
    "Attis" => PersonaData { level: 82, arcana: Arcana::Hanged },
    "Baal" => PersonaData { level: 82, arcana: Arcana::Emperor },
    "Baphomet" => PersonaData { level: 58, arcana: Arcana::Devil },
    "Barong" => PersonaData { level: 52, arcana: Arcana::Emperor },
    "Beelzebub" => PersonaData { level: 87, arcana: Arcana::Devil },
    "Belial" => PersonaData { level: 82, arcana: Arcana::Devil },
    "Belphegor" => PersonaData { level: 37, arcana: Arcana::Tower },
    "Berith" => PersonaData { level: 9, arcana: Arcana::Hierophant },
    "Bicorn" => PersonaData { level: 4, arcana: Arcana::Hermit },
    "Bishamonten" => PersonaData { level: 67, arcana: Arcana::Hierophant },
    "Black Frost" => PersonaData { level: 67, arcana: Arcana::Fool },
    "Black Ooze" => PersonaData { level: 18, arcana: Arcana::Moon },
    "Black Rider" => PersonaData { level: 59, arcana: Arcana::Tower },
    "Bugs" => PersonaData { level: 49, arcana: Arcana::Fool },
    "Byakhee" => PersonaData { level: 70, arcana: Arcana::Moon },
    "Byakko" => PersonaData { level: 45, arcana: Arcana::Temperance },
    "Cait Sith" => PersonaData { level: 5, arcana: Arcana::Magician },
    "Cerberus" => PersonaData { level: 55, arcana: Arcana::Chariot },
    "Chernobog" => PersonaData { level: 62, arcana: Arcana::Death },
    "Chi You" => PersonaData { level: 88, arcana: Arcana::Chariot },
    "Chimera" => PersonaData { level: 74, arcana: Arcana::Strength },
    "Choronzon" => PersonaData { level: 28, arcana: Arcana::Magician },
    "Clotho" => PersonaData { level: 27, arcana: Arcana::Fortune },
    "Crystal Skull" => PersonaData { level: 50, arcana: Arcana::Fool },
    "Cu Chulainn" => PersonaData { level: 76, arcana: Arcana::Faith },
    "Cybele" => PersonaData { level: 83, arcana: Arcana::Priestess },
    "Daisoujou" => PersonaData { level: 40, arcana: Arcana::Hierophant },
    "Dakini" => PersonaData { level: 50, arcana: Arcana::Empress },
    "Decarabia" => PersonaData { level: 32, arcana: Arcana::Councillor },
    "Dionysus" => PersonaData { level: 71, arcana: Arcana::Councillor },
    "Dominion" => PersonaData { level: 68, arcana: Arcana::Justice },
    "Eligor" => PersonaData { level: 16, arcana: Arcana::Emperor },
    "Emperor's Amulet" => PersonaData { level: 35, arcana: Arcana::Hanged },
    "Fafnir" => PersonaData { level: 86, arcana: Arcana::Hermit },
    "Flauros" => PersonaData { level: 19, arcana: Arcana::Devil },
    "Forneus" => PersonaData { level: 63, arcana: Arcana::Magician },
    "Fortuna" => PersonaData { level: 46, arcana: Arcana::Fortune },
    "Futsunushi" => PersonaData { level: 86, arcana: Arcana::Magician },
    "Fuu-Ki" => PersonaData { level: 23, arcana: Arcana::Star },
    "Gabriel" => PersonaData { level: 77, arcana: Arcana::Temperance },
    "Ganesha" => PersonaData { level: 53, arcana: Arcana::Sun },
    "Garuda" => PersonaData { level: 52, arcana: Arcana::Star },
    "Genbu" => PersonaData { level: 7, arcana: Arcana::Temperance },
    "Girimehkala" => PersonaData { level: 43, arcana: Arcana::Moon },
    "Hanuman" => PersonaData { level: 64, arcana: Arcana::Strength },
    "Hariti" => PersonaData { level: 40, arcana: Arcana::Empress },
    "Hastur" => PersonaData { level: 84, arcana: Arcana::Star },
    "Hecatoncheires" => PersonaData { level: 42, arcana: Arcana::Hanged },
    "Hell Biker" => PersonaData { level: 37, arcana: Arcana::Death },
    "High Pixie" => PersonaData { level: 16, arcana: Arcana::Fool },
    "Hope Diamond" => PersonaData { level: 40, arcana: Arcana::Death },
    "Horus" => PersonaData { level: 47, arcana: Arcana::Sun },
    "Hua Po" => PersonaData { level: 9, arcana: Arcana::Hanged },
    "Incubus" => PersonaData { level: 5, arcana: Arcana::Devil },
    "Inugami" => PersonaData { level: 14, arcana: Arcana::Hanged },
    "Ippon-Datara" => PersonaData { level: 13, arcana: Arcana::Hermit },
    "Ishtar" => PersonaData { level: 85, arcana: Arcana::Lovers },
    "Isis" => PersonaData { level: 26, arcana: Arcana::Priestess },
    "Jack Frost" => PersonaData { level: 11, arcana: Arcana::Magician },
    "Jack-o'-Lantern" => PersonaData { level: 2, arcana: Arcana::Magician },
    "Jatayu" => PersonaData { level: 51, arcana: Arcana::Hanged },
    "Jikokuten" => PersonaData { level: 22, arcana: Arcana::Temperance },
    "Kaiwan" => PersonaData { level: 36, arcana: Arcana::Star },
    "Kali" => PersonaData { level: 63, arcana: Arcana::Empress },
    "Kelpie" => PersonaData { level: 6, arcana: Arcana::Strength },
    "Kikuri-Hime" => PersonaData { level: 40, arcana: Arcana::Priestess },
    "Kin-Ki" => PersonaData { level: 25, arcana: Arcana::Chariot },
    "King Frost" => PersonaData { level: 61, arcana: Arcana::Emperor },
    "Kodama" => PersonaData { level: 11, arcana: Arcana::Star },
    "Koh-i-Noor" => PersonaData { level: 25, arcana: Arcana::Priestess },
    "Kohryu" => PersonaData { level: 76, arcana: Arcana::Hierophant },
    "Koppa Tengu" => PersonaData { level: 11, arcana: Arcana::Temperance },
    "Koropokkuru" => PersonaData { level: 9, arcana: Arcana::Hermit },
    "Koumokuten" => PersonaData { level: 49, arcana: Arcana::Hermit },
    "Kumbhanda" => PersonaData { level: 42, arcana: Arcana::Hermit },
    "Kurama Tengu" => PersonaData { level: 31, arcana: Arcana::Hermit },
    "Kushinada" => PersonaData { level: 42, arcana: Arcana::Lovers },
    "Kushi Mitama" => PersonaData { level: 12, arcana: Arcana::Councillor },
    "Lachesis" => PersonaData { level: 35, arcana: Arcana::Fortune },
    "Lakshmi" => PersonaData { level: 69, arcana: Arcana::Fortune },
    "Lamia" => PersonaData { level: 26, arcana: Arcana::Empress },
    "Leanan Sidhe" => PersonaData { level: 19, arcana: Arcana::Lovers },
    "Legion" => PersonaData { level: 38, arcana: Arcana::Fool },
    "Lilim" => PersonaData { level: 32, arcana: Arcana::Devil },
    "Lilith" => PersonaData { level: 60, arcana: Arcana::Moon },
    "Loa" => PersonaData { level: 70, arcana: Arcana::Hermit },
    "Lucifer" => PersonaData { level: 93, arcana: Arcana::Star },
    "Macabre" => PersonaData { level: 73, arcana: Arcana::Hanged },
    "Mada" => PersonaData { level: 90, arcana: Arcana::Tower },
    "Makami" => PersonaData { level: 15, arcana: Arcana::Temperance },
    "Mandrake" => PersonaData { level: 3, arcana: Arcana::Death },
    "Mara" => PersonaData { level: 73, arcana: Arcana::Tower },
    "Maria" => PersonaData { level: 93, arcana: Arcana::Faith },
    "Matador" => PersonaData { level: 17, arcana: Arcana::Death },
    "Melchizedek" => PersonaData { level: 58, arcana: Arcana::Justice },
    "Metatron" => PersonaData { level: 89, arcana: Arcana::Justice },
    "Michael" => PersonaData { level: 87, arcana: Arcana::Judgement },
    "Mishaguji" => PersonaData { level: 52, arcana: Arcana::Hierophant },
    "Mithra" => PersonaData { level: 33, arcana: Arcana::Temperance },
    "Mithras" => PersonaData { level: 39, arcana: Arcana::Sun },
    "Mokoi" => PersonaData { level: 9, arcana: Arcana::Death },
    "Moloch" => PersonaData { level: 60, arcana: Arcana::Hanged },
    "Mot" => PersonaData { level: 72, arcana: Arcana::Death },
    "Mother Harlot" => PersonaData { level: 85, arcana: Arcana::Empress },
    "Mothman" => PersonaData { level: 33, arcana: Arcana::Moon },
    "Naga" => PersonaData { level: 24, arcana: Arcana::Hermit },
    "Narcissus" => PersonaData { level: 48, arcana: Arcana::Lovers },
    "Nebiros" => PersonaData { level: 74, arcana: Arcana::Devil },
    "Neko Shogun" => PersonaData { level: 30, arcana: Arcana::Star },
    "Nekomata" => PersonaData { level: 17, arcana: Arcana::Magician },
    "Nigi Mitama" => PersonaData { level: 22, arcana: Arcana::Councillor },
    "Norn" => PersonaData { level: 52, arcana: Arcana::Fortune },
    "Nue" => PersonaData { level: 20, arcana: Arcana::Death },
    "Obariyon" => PersonaData { level: 8, arcana: Arcana::Fool },
    "Oberon" => PersonaData { level: 66, arcana: Arcana::Emperor },
    "Odin" => PersonaData { level: 84, arcana: Arcana::Emperor },
    "Okuninushi" => PersonaData { level: 54, arcana: Arcana::Faith },
    "Ongyo-Ki" => PersonaData { level: 89, arcana: Arcana::Hermit },
    "Oni" => PersonaData { level: 20, arcana: Arcana::Strength },
    "Onmoraki" => PersonaData { level: 12, arcana: Arcana::Moon },
    "Orichalcum" => PersonaData { level: 60, arcana: Arcana::Faith },
    "Orlov" => PersonaData { level: 30, arcana: Arcana::Strength },
    "Orobas" => PersonaData { level: 17, arcana: Arcana::Hierophant },
    "Orthrus" => PersonaData { level: 21, arcana: Arcana::Hanged },
    "Ose" => PersonaData { level: 42, arcana: Arcana::Fool },
    "Pale Rider" => PersonaData { level: 54, arcana: Arcana::Death },
    "Parvati" => PersonaData { level: 56, arcana: Arcana::Lovers },
    "Pazuzu" => PersonaData { level: 45, arcana: Arcana::Devil },
    "Phoenix" => PersonaData { level: 21, arcana: Arcana::Faith },
    "Pisaca" => PersonaData { level: 28, arcana: Arcana::Death },
    "Pixie" => PersonaData { level: 2, arcana: Arcana::Lovers },
    "Power" => PersonaData { level: 41, arcana: Arcana::Justice },
    "Principality" => PersonaData { level: 29, arcana: Arcana::Justice },
    "Queen Mab" => PersonaData { level: 43, arcana: Arcana::Magician },
    "Queen's Necklace" => PersonaData { level: 15, arcana: Arcana::Empress },
    "Quetzalcoatl" => PersonaData { level: 66, arcana: Arcana::Sun },
    "Raja Naga" => PersonaData { level: 55, arcana: Arcana::Temperance },
    "Rakshasa" => PersonaData { level: 24, arcana: Arcana::Strength },
    "Rangda" => PersonaData { level: 48, arcana: Arcana::Magician },
    "Raphael" => PersonaData { level: 78, arcana: Arcana::Lovers },
    "Red Rider" => PersonaData { level: 41, arcana: Arcana::Tower },
    "Regent" => PersonaData { level: 10, arcana: Arcana::Emperor },
    "Saki Mitama" => PersonaData { level: 6, arcana: Arcana::Lovers },
    "Sandalphon" => PersonaData { level: 75, arcana: Arcana::Moon },
    "Sandman" => PersonaData { level: 23, arcana: Arcana::Magician },
    "Sarasvati" => PersonaData { level: 50, arcana: Arcana::Priestess },
    "Satan" => PersonaData { level: 92, arcana: Arcana::Judgement },
    "Satanael" => PersonaData { level: 95, arcana: Arcana::Fool },
    "Scathach" => PersonaData { level: 77, arcana: Arcana::Priestess },
    "Seiryu" => PersonaData { level: 62, arcana: Arcana::Councillor },
    "Setanta" => PersonaData { level: 25, arcana: Arcana::Emperor },
    "Seth" => PersonaData { level: 51, arcana: Arcana::Tower },
    "Shiisaa" => PersonaData { level: 15, arcana: Arcana::Strength },
    "Shiki-Ouji" => PersonaData { level: 18, arcana: Arcana::Chariot },
    "Shiva" => PersonaData { level: 82, arcana: Arcana::Judgement },
    "Siegfried" => PersonaData { level: 84, arcana: Arcana::Faith },
    "Silky" => PersonaData { level: 6, arcana: Arcana::Priestess },
    "Skadi" => PersonaData { level: 53, arcana: Arcana::Priestess },
    "Slime" => PersonaData { level: 10, arcana: Arcana::Chariot },
    "Sraosha" => PersonaData { level: 80, arcana: Arcana::Star },
    "Stone of Scone" => PersonaData { level: 20, arcana: Arcana::Fortune },
    "Succubus" => PersonaData { level: 7, arcana: Arcana::Moon },
    "Sudama" => PersonaData { level: 17, arcana: Arcana::Hermit },
    "Sui-Ki" => PersonaData { level: 24, arcana: Arcana::Moon },
    "Surt" => PersonaData { level: 83, arcana: Arcana::Magician },
    "Suzaku" => PersonaData { level: 16, arcana: Arcana::Sun },
    "Take-Minakata" => PersonaData { level: 26, arcana: Arcana::Hanged },
    "Tam Lin" => PersonaData { level: 27, arcana: Arcana::Faith },
    "Thor" => PersonaData { level: 64, arcana: Arcana::Chariot },
    "Thoth" => PersonaData { level: 36, arcana: Arcana::Emperor },
    "Throne" => PersonaData { level: 72, arcana: Arcana::Justice },
    "Thunderbird" => PersonaData { level: 34, arcana: Arcana::Sun },
    "Titania" => PersonaData { level: 56, arcana: Arcana::Empress },
    "Trumpeter" => PersonaData { level: 59, arcana: Arcana::Judgement },
    "Unicorn" => PersonaData { level: 39, arcana: Arcana::Faith },
    "Uriel" => PersonaData { level: 81, arcana: Arcana::Justice },
    "Valkyrie" => PersonaData { level: 44, arcana: Arcana::Strength },
    "Vasuki" => PersonaData { level: 68, arcana: Arcana::Star },
    "Vishnu" => PersonaData { level: 83, arcana: Arcana::Fool },
    "Vohu Manah" => PersonaData { level: 80, arcana: Arcana::Councillor },
    "White Rider" => PersonaData { level: 38, arcana: Arcana::Chariot },
    "Yaksini" => PersonaData { level: 20, arcana: Arcana::Empress },
    "Yamata-no-Orochi" => PersonaData { level: 64, arcana: Arcana::Judgement },
    "Yatagarasu" => PersonaData { level: 57, arcana: Arcana::Councillor },
    "Yoshitsune" => PersonaData { level: 87, arcana: Arcana::Tower },
    "Yurlungur" => PersonaData { level: 43, arcana: Arcana::Sun },
    "Zaou-Gongen" => PersonaData { level: 80, arcana: Arcana::Strength },
    "Zouchouten" => PersonaData { level: 31, arcana: Arcana::Strength },
    "Ariadne" => PersonaData { level: 30, arcana: Arcana::Fortune },
    "Ariadne Picaro" => PersonaData { level: 42, arcana: Arcana::Fortune },
    "Asterius" => PersonaData { level: 56, arcana: Arcana::Fortune },
    "Asterius Picaro" => PersonaData { level: 62, arcana: Arcana::Fortune },
    "Athena" => PersonaData { level: 46, arcana: Arcana::Chariot },
    "Athena Picaro" => PersonaData { level: 50, arcana: Arcana::Chariot },
    "Izanagi" => PersonaData { level: 20, arcana: Arcana::Fool },
    "Izanagi Picaro" => PersonaData { level: 23, arcana: Arcana::Fool },
    "Izanagi-no-Okami" => PersonaData { level: 80, arcana: Arcana::World },
    "Izanagi-no-Okami Picaro" => PersonaData { level: 89, arcana: Arcana::World },
    "Kaguya" => PersonaData { level: 16, arcana: Arcana::Moon },
    "Kaguya Picaro" => PersonaData { level: 25, arcana: Arcana::Moon },
    "Magatsu-Izanagi" => PersonaData { level: 44, arcana: Arcana::Tower },
    "Magatsu-Izanagi Picaro" => PersonaData { level: 48, arcana: Arcana::Tower },
    "Messiah" => PersonaData { level: 81, arcana: Arcana::Judgement },
    "Messiah Picaro" => PersonaData { level: 90, arcana: Arcana::Judgement },
    "Orpheus" => PersonaData { level: 26, arcana: Arcana::Fool },
    "Orpheus F" => PersonaData { level: 11, arcana: Arcana::Fool },
    "Orpheus F Picaro" => PersonaData { level: 13, arcana: Arcana::Fool },
    "Orpheus Picaro" => PersonaData { level: 29, arcana: Arcana::Fool },
    "Raoul" => PersonaData { level: 76, arcana: Arcana::Fool },
    "Thanatos" => PersonaData { level: 65, arcana: Arcana::Death },
    "Thanatos Picaro" => PersonaData { level: 69, arcana: Arcana::Death },
    "Tsukiyomi" => PersonaData { level: 50, arcana: Arcana::Moon },
    "Tsukiyomi Picaro" => PersonaData { level: 55, arcana: Arcana::Moon },
};

pub static SPECIAL_PERSONAS: phf::Map<&'static str, phf::Set<&'static str>> = phf_map! {
    "Alice" => phf_set! { "Belial", "Nebiros"},
    "Ardha" => phf_set! { "Shiva", "Parvati"},
    "Asura" => phf_set! { "Jikokuten", "Zouchouten", "Koumokuten", "Bishamonten"},
    "Black Frost" => phf_set! { "Jack-o'-Lantern", "Jack Frost", "King Frost"},
    "Bugs" => phf_set! { "Pixie", "Pisaca", "Hariti"},
    "Chi You" => phf_set! { "White Rider", "Hecatoncheires", "Thor", "Cu Chulainn", "Yoshitsune"},
    "Flauros" => phf_set! { "Berith", "Eligor", "Orobas"},
    "Hell Biker" => phf_set! { "Archangel", "Matador", "Decarabia"},
    "Izanagi-no-Okami" => phf_set! { "Yamata-no-Orochi", "Throne", "Inugami", "Raja Naga", "Barong", "Norn"},
    "Izanagi-no-Okami Picaro" => phf_set! { "Okuninushi", "Orthrus", "Kali", "Mithras", "Cu Chulainn", "Lucifer"},
    "Kohryu" => phf_set! { "Seiryu", "Byakko", "Suzaku", "Genbu"},
    "Lucifer" => phf_set! { "Anubis", "Ananta", "Trumpeter", "Michael", "Metatron", "Satan"},
    "Metatron" => phf_set! { "Principality", "Power", "Dominion", "Melchizedek", "Sandalphon", "Michael"},
    "Michael" => phf_set! { "Gabriel", "Raphael", "Uriel"},
    "Neko Shogun" => phf_set! { "Kodama", "Sudama", "Anzu"},
    "Ongyo-Ki" => phf_set! { "Kin-Ki", "Sui-Ki", "Fuu-Ki"},
    "Satanael" => phf_set! { "Arsène", "Anzu", "Ishtar", "Satan", "Lucifer", "Michael"},
    "Seth" => phf_set! { "Isis", "Anubis", "Thoth", "Horus"},
    "Shiva" => phf_set! { "Barong", "Rangda"},
    "Sraosha" => phf_set! { "Mithra", "Mithras", "Melchizedek", "Lilith", "Gabriel"},
    "Tam Lin" => phf_set! { "Cait Sith", "High Pixie", "Leanan Sidhe"},
    "Trumpeter" => phf_set! { "White Rider", "Red Rider", "Black Rider", "Pale Rider"},
    "Vasuki" => phf_set! { "Naga", "Ananta", "Raja Naga"},
    "Yoshitsune" => phf_set! { "Shiki-Ouji", "Arahabaki", "Okuninushi", "Yatagarasu", "Futsunushi"},
};
